; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
lib_deps = 
	h2zero/NimBLE-Arduino@^2.1.0
	fastled/FastLED@^3.10.3
	https://github.com/bolderflight/invensense-imu@^6.0.3
build_flags = 
	-DESP32_TARGET
	-D USE_ESP32_DRIVER

build_src_flags = 
	-Wall
	-Wextra
	-Werror=return-type
	-Werror=switch
	-Wswitch-enum
	-Werror=address
	-Wshadow

; if you need to change the IP address settings etc,
; you need to uncomment OTA settings

; 	; --- OTA settings ---
; upload_protocol = espota
; upload_port = 192.168.0.159   ; IP address of the ESP32 to update via WiFi
; upload_flags =
;     --auth=admin             ; Set the OTA password (must match the one in your program)

; --- Serial monitor settings ---
monitor_speed = 115200